apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu-mongos
  namespace: default
spec:
  mode: one
  selector:
    labelSelectors:
      'role': mongos
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: '10m'