apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu-hpa
spec:
  mode: one
  selector:
    labelSelectors:
      'app': flask
  stressors:
    cpu:
      workers: 4
      load: 100 # Carica la CPU al 100%
  duration: '10m'