apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-mongodb-shard
  namespace: default
spec:
  mode: all
  selector:
    labelSelectors:
      'role': mongos   # ora targetta il mongos invece di shard1
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: '5m'