apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: periodic-pod-kill-mongos
  namespace: default
spec:
  schedule: '@every 2m'
  historyLimit: 5
  concurrencyPolicy: "Forbid"
  type: 'PodChaos'
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - default
      labelSelectors:
        'role': 'mongos'
