apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: my-release
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
  - port: web
    path: /metrics
    interval: 15s