apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongo-sharded
spec:
  replsets:
    - name: shard1
      size: 3
    - name: shard2
      size: 3

  sharding:
    enabled: true

    mongos:
      size: 1

    configsvrReplSet:
      size: 3