apiVersion: v1
kind: Service
metadata:
  name: shard1
spec:
  clusterIP: None
  selector:
    app: shard1
  ports:
    - name: mongo
      port: 27018
      targetPort: 27018
---
apiVersion: v1
kind: Service
metadata:
  name: mongos
spec:
  selector:
    role: mongos
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017